# Generated by Django 4.1.4 on 2022-12-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('receipt_number', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transaction')),
            ],
            options={
                'unique_together': {('transaction_id', 'product_id')},
            },
        ),
    ]
