NO_PRIVILEGE = 0

PRODUCT_NAME = 0b00000001
PRODUCT_CATEGORY = 0b00000010
PRODUCT_DESCRIPTION = 0b00000100
PRODUCT_PRICE = 0b00001000
PRODUCT_STOCK = 0b00010000
TRANSACTION = 0b00100000

PRODUCT_GENERAL = PRODUCT_NAME|PRODUCT_CATEGORY|PRODUCT_DESCRIPTION

INFO_PRIVILEGES = {
    'Management': PRODUCT_GENERAL|PRODUCT_PRICE|PRODUCT_STOCK|TRANSACTION,
    'Development': PRODUCT_GENERAL|TRANSACTION,
    'Finance': PRODUCT_GENERAL|PRODUCT_PRICE|PRODUCT_STOCK|TRANSACTION,
    'Storage': PRODUCT_GENERAL|PRODUCT_STOCK|TRANSACTION,
    'Production': PRODUCT_GENERAL|PRODUCT_STOCK,
    'Sales': PRODUCT_GENERAL|PRODUCT_PRICE|PRODUCT_STOCK
}

EDIT_PRIVILEGES = {
    'Management': PRODUCT_GENERAL|PRODUCT_PRICE|TRANSACTION,
    'Development': NO_PRIVILEGE,
    'Finance': PRODUCT_PRICE,
    'Storage': PRODUCT_GENERAL|TRANSACTION,
    'Production': NO_PRIVILEGE,
    'Sales': NO_PRIVILEGE
}