# Generated by Django 4.1.4 on 2022-12-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
