# Generated by Django 4.1.4 on 2022-12-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('phone_number', models.TextField()),
                ('address', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
